on:
  push:
    branches:
      - main  # or whatever branch you want to trigger this on

jobs:
  unit-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Specify the action to checkout code

      - name: Install dependencies
        run:  pip install -r requirements.txt

      - name: Run tests
        run: pytest